-- PostgreSQL Production Database Schema for AeroCold Logistics Technologies
-- Domain Architecture: Fleet Dispatch & Telematics Control (logistics)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "We transport temperature-sensitive biologics and vaccines across 45 tier-1 and tier-2 hubs. 14% of shipments encounter temperature excursion breaches (+2°C to +8°C threshold violation) due to uncalibrated reefer containers, manual paper temperature loggers, and delayed driver handover reporting. We need a real-time IoT cold-chain telemetry platform that alerts dispatchers before spoilage occurs, automates digital CDSCO/FDA compliance audits, and dynamically re-routes trucks to the nearest cold-storage warehouse."

CREATE TABLE IF NOT EXISTS public.logistics_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Origin → Destination Hub
  col2_data TEXT NOT NULL, -- Semantic Mapping: Fleet Vehicle & Speed
  status TEXT NOT NULL,    -- Semantic Mapping: Transit Status
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Assigned Driver
  metric_value TEXT NOT NULL, -- Semantic Mapping: ETA Turnaround
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.logistics_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.logistics_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.logistics_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.logistics_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.logistics_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
